-- MySQL Script generated by MySQL Workbench
-- Wed Aug 31 18:52:31 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema challenge_java
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `challenge_java` ;

-- -----------------------------------------------------
-- Schema challenge_java
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `challenge_java` DEFAULT CHARACTER SET utf8 ;
USE `challenge_java` ;

-- -----------------------------------------------------
-- Table `challenge_java`.`personajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `challenge_java`.`personajes` (
  `id_personajes` INT NOT NULL AUTO_INCREMENT,
  `nombre_personaje` VARCHAR(45) NOT NULL,
  `imagen` VARCHAR(200) NULL,
  `edad` INT NOT NULL,
  `peso` DECIMAL(2) NOT NULL,
  `historia` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_personajes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `challenge_java`.`peliculas_series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `challenge_java`.`peliculas_series` (
  `id_peliculas_series` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `fecha_creacion` DATE NOT NULL,
  `calificacion` INT(5) NULL,
  PRIMARY KEY (`id_peliculas_series`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `challenge_java`.`rel_personajes_peliculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `challenge_java`.`rel_personajes_peliculas` (
  `id_rel_personaje_pelicula` INT NOT NULL AUTO_INCREMENT,
  `tblpersonaje_id_personaje` INT NOT NULL,
  `tblpeliculas_id_peliculas_series` INT NOT NULL,
  PRIMARY KEY (`id_rel_personaje_pelicula`),
  CONSTRAINT `ref_relpersonapelicula_personaje`
    FOREIGN KEY (`tblpersonaje_id_personaje`)
    REFERENCES `challenge_java`.`personajes` (`id_personajes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ref_relpersonajepelicula_peliculasseries`
    FOREIGN KEY (`tblpeliculas_id_peliculas_series`)
    REFERENCES `challenge_java`.`peliculas_series` (`id_peliculas_series`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `ref_relpersonapelicula_personaje_idx` ON `challenge_java`.`rel_personajes_peliculas` (`tblpersonaje_id_personaje` ASC) VISIBLE;

CREATE INDEX `ref_relpersonajepelicula_peliculasseries_idx` ON `challenge_java`.`rel_personajes_peliculas` (`tblpeliculas_id_peliculas_series` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `challenge_java`.`generos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `challenge_java`.`generos` (
  `id_genero` INT NOT NULL AUTO_INCREMENT,
  `nombre_genero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_genero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `challenge_java`.`rel_generos_peliculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `challenge_java`.`rel_generos_peliculas` (
  `id_rel_generos_peliculas` INT NOT NULL AUTO_INCREMENT,
  `tblgeneros_id_generos` INT NOT NULL,
  `tblpeliculasseries_id_peliculas_series` INT NOT NULL,
  PRIMARY KEY (`id_rel_generos_peliculas`),
  CONSTRAINT `ref_relgenerospeliculas_generos`
    FOREIGN KEY (`tblgeneros_id_generos`)
    REFERENCES `challenge_java`.`generos` (`id_genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ref_relgenerospeliculas_idpeliculasseries`
    FOREIGN KEY (`tblpeliculasseries_id_peliculas_series`)
    REFERENCES `challenge_java`.`peliculas_series` (`id_peliculas_series`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `ref_relgenerospeliculas_generos_idx` ON `challenge_java`.`rel_generos_peliculas` (`tblgeneros_id_generos` ASC) VISIBLE;

CREATE INDEX `ref_relgenerospeliculas_idpeliculasseries_idx` ON `challenge_java`.`rel_generos_peliculas` (`tblpeliculasseries_id_peliculas_series` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
